export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const CLEAR_SESSION = "CLEAR_SESSION";
export const OVERRIDE_USER_ACTION = "OVERRIDE_USER_ACTION";
