const KOTA_TMP = [
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Gresik",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Surabaya",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Jakarta",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Batam",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Tanjung Pinang",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Belakang Padang",
    isActive: Math.floor(Math.random() * 2),
  },
];

const PENANDA_TANGAN_TMP = [
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Jack",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Arifin",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Sudirman",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Lintang",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Aswin",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Arif",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Virgi",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Jerry",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Boy",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Lina",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Agus",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Ludi",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    nip: Math.floor(Math.random() * 1000000),
    name: "Kevin",
    position: "Senior",
    isActive: Math.floor(Math.random() * 2),
  },
];

const PENGGUNA_TMP = [
  {
    id: Math.floor(Math.random() * 1000),
    key: Math.floor(Math.random() * 1000),
    name: "Faid Hamburger",
    username: "hamburger",
    position: ".tbk",
    password: Math.random().toString(36).substring(2),
    isActive: Math.floor(Math.random() * 2),
  },
];

export { KOTA_TMP, PENANDA_TANGAN_TMP, PENGGUNA_TMP };
